name: Main Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build 
        run: dotnet build HelloWorld/HelloWorld.csproj

      - name: Test
        run: dotnet test Tests/Tests.csproj 

      - name: Run
        run: dotnet run --project HelloWorld/HelloWorld.csproj

      - name: Cleaning
        run: find . -type d \( -name "bin" -o -name "obj" \) -exec rm -r {} +