name: Main Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and Run Project
        run: dotnet run

      - name: Cleaning
        run: find . -type d \( -name "bin" -o -name "obj" \) -exec rm -r {} +